import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import './globals.css'
import { Poppins, Rancho, Lobster_Two } from 'next/font/google'

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-poppins',
})

const rancho = Rancho({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-rancho',
})

const lobster = Lobster_Two({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-lobster',
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${poppins.variable}  ${rancho.variable} ${lobster.variable}`}>
      <body>
        {children}
      </body>
    </html>
  );
}
